---

nginx:
  container_name: nginx
  # build: ./
  image: openresty:dev
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./vol/conf:/etc/nginx/conf.d
    - ./vol/certs:/etc/nginx/certs
    - ./vol/lua:/etc/nginx/lua
  environment:
    VAULT_ADDR: $VAULT_ADDR
    LOG_LEVEL: debug
    OPENRESTY_LOG_LEVEL: debug
    GRAYLOG_ENABLED: 'no'
    VTS_ENABLED: 'no'
  ports:
    - 80:80
    - 443:443
    - 44380:44380


test_service:
  container_name: test_service
  image: testing/request_headers
  environment:
    SERVICE_FQDN: test.example.com
    AUTH_CERT_BUNDLE: /usr/local/share/ca-certificates/vault-bundle.crt
    # # posix group:  cn=admins,ou=groups,dc=example,dc=com
    REQUIRED_GROUP: admins
  labels:
    openresty.skip_root_location: True
    openresty.render_confs: True
